name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main # 当推送到主分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 使用指定的 Node.js 版本

      # Step 3: 安装 Hexo 和依赖项
      - name: Install Hexo and dependencies
        run: |
          npm install -g hexo-cli
          npm install

      # Step 4: 生成静态文件
      - name: Generate static files
        run: hexo generate

      # Step 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hexo 生成的静态文件目录
          publish_branch: gh-pages # 部署的目标分支
          cname: elysia.cloud-ip.biz
